#!/usr/bin/env node
// Style Dictionary v4 build script.
//
// Uses one StyleDictionary instance per mode so the light and dark semantic
// files never collide in the internal dictionary. Emits:
//   - src/styles/tokens.light.css
//   - src/styles/tokens.dark.css
//   - src/tokens/generated.ts   (resolved light-mode values, for docs)

import StyleDictionary from "style-dictionary";

const SELECTOR = { light: ":root", dark: ":root[data-theme=\"dark\"]" };

function cssVarsFormat(mode) {
  return ({ dictionary }) => {
    const lines = dictionary.allTokens
      .slice()
      .sort((a, b) => a.name.localeCompare(b.name))
      .map((t) => `  --${t.name}: ${t.$value ?? t.value};`)
      .join("\n");
    return [
      "/* Generated by Style Dictionary — do not edit. */",
      `/* Theme: ${mode}. Source: tokens/raw/primitives.json + semantic.${mode}.json */`,
      `${SELECTOR[mode]} {`,
      lines,
      "}",
      "",
    ].join("\n");
  };
}

StyleDictionary.registerFormat({ name: "css/theme-vars/light", format: cssVarsFormat("light") });
StyleDictionary.registerFormat({ name: "css/theme-vars/dark",  format: cssVarsFormat("dark")  });

StyleDictionary.registerFormat({
  name: "js/tokens-record",
  format: ({ dictionary }) => {
    const grouped = {};
    for (const t of dictionary.allTokens) {
      const [top] = t.path;
      grouped[top] ??= {};
      grouped[top][t.name] = t.$value ?? t.value;
    }
    return [
      "/* Generated by Style Dictionary — do not edit. */",
      `export const tokens = ${JSON.stringify(grouped, null, 2)} as const;`,
      "export type TokenGroup = keyof typeof tokens;",
      "",
    ].join("\n");
  },
});

function makeConfig(mode) {
  return {
    log: { verbosity: "silent", warnings: "disabled" },
    source: [
      "tokens/raw/primitives.json",
      "tokens/raw/palette.rich.json",
      `tokens/raw/semantic.${mode}.json`,
    ],
    platforms: {
      css: {
        transformGroup: "css",
        buildPath: "src/styles/",
        files: [{ destination: `tokens.${mode}.css`, format: `css/theme-vars/${mode}` }],
      },
      ...(mode === "light"
        ? {
            js: {
              transformGroup: "js",
              buildPath: "src/tokens/",
              files: [{ destination: "generated.ts", format: "js/tokens-record" }],
            },
          }
        : {}),
    },
  };
}

for (const mode of ["light", "dark"]) {
  const sd = new StyleDictionary(makeConfig(mode));
  await sd.hasInitialized;
  await sd.buildAllPlatforms();
  console.log(`✓ built ${mode}`);
}
